revisionHistoryLimit: 0

here:
  appId: 2co0Y0HOLhfE29QW7txZ
  appCode: HmygqYb94UdgW_zdD6797g

image:
  registry: fbdevfalcon.azurecr.io
  name: here-monitoring
  version: latest
  imagePullPolicy: Always

deployment:
  replicas: 1
  port: 80
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 1Gi
      cpu: 1

# ingress can be enabled for debugging
ingress:
  enabled: false
  host: here-monitoring.dev.azure.fleetboard.net